### ISSUE TITLE
character doesn't show correctly

### ISSUE THREAD

**Issue by Starslayerx** [nschloe/purple-pi#16]
```latex
l_{i}=\prod_{\frac{x-x_{j}}{j=0,j\neq i}}^{n}
```
![s](https://user-images.githubusercontent.com/53030987/111913998-36e5c280-8aab-11eb-8a7d-a94eb4adbb42.png)

**Comment by nschloe** [comment]
What's the problem?

**Comment by Starslayerx** [comment]
Maybe it should seems like this?
![image](https://user-images.githubusercontent.com/53030987/111940138-f61c9680-8b08-11eb-9e27-1a7c94be29ee.png)

**Comment by nschloe** [comment]
That's a different forumula. What do you mean exactly?

**Comment by Starslayerx** [comment]
Such as the first expressino, 'n' in not at the top of the chararcter, but top right corner.
The second 'n' is at the top and 'i=0' at the bottom, which is what I want.

**Comment by nschloe** [comment]
That's the difference between inline and display math.
