### ISSUE TITLE
allow website to set activation tag

### ISSUE THREAD

**Issue by nschloe** [nschloe/purple-pi#4]
If the tag is found, green-pi is enabled by default. One can also make the syntax (`$` vs `\(`) configurable.

**Comment by diegoferigo** [comment]
Hi @nschloe, thank you for the great work you've done with this extension (Firefox support too :heart_eyes:). Being able to use the `$$` delimiter for inline latex would be a great addition, it there any way to enable it?

**Comment by nschloe** [comment]
I'm working on something right now. How are you using Green Pi?

**Comment by diegoferigo** [comment]
I discovered it recently and I'm evaluating the substitution of [traversaro/github-mathjax-firefox](https://github.com/traversaro/github-mathjax-firefox), but the `$$` delimiter is a blocking factor for me and few colleagues of mine since we have a lot of documentation that already use that format.

**Comment by nschloe** [comment]
Fixed by #5.

**Comment by nschloe** [comment]
@diegoferigo I just updated Green Pi to let the site author decide if and how math should be displayed. Dollar `$` delimiters included; see the readme.

**Comment by diegoferigo** [comment]
Thanks for the prompt feedback! I just updated the extension to the latest 0.1.0 version and it does work in the README of the project. However, it does not seem to render the math from the issues. Test below.

[Test link](https://github.com/nschloe/green-pi?activate&inlineMath=$) with the enabled delimiter.

---

Let $U$ be an open subset of the complex plane $\mathbb{C}$, and suppose the closed disk $D$ defined as
$$
D = \bigl\\{z:|z-z_{0}|\leq r\bigr\\}
$$
is completely contained in $U$. Let $f: U\to\mathbb{C}$ be a holomorphic function, and let $\gamma$ be the circle, oriented counterclockwise, forming the boundary of $D$.
Then for every $a$ in the interior of $D$,
$$
f(a) = \frac{1}{2\pi i} \oint _{\gamma}\frac{f(z)}{z-a} dz.
$$

**Comment by nschloe** [comment]
Absolutely. You need the badge in the page.

_Edit:_ Ah wait. You _do_ have have the link.

**Comment by diegoferigo** [comment]
Ow ok now I got it: [![green-pi](https://img.shields.io/badge/Rendered%20with-Green%20Pi-00d5b1?style=flat-square)](https://github.com/nschloe/green-pi?activate&inlineMath=$)

**Comment by nschloe** [comment]
You're right, but it should also work with a plain link that you had before. I'll look at it later.

**Comment by nschloe** [comment]
Let me delete your last comment so I can debug. :smiley_cat:

**Comment by nschloe** [comment]
Okay yeah, your link is to `https://github.com/nschloe/green-pi/issues/4`. Remove the `issues/4` part and it should work.

**Comment by diegoferigo** [comment]
> Okay yeah, your link is to https://github.com/nschloe/green-pi/issues/4. Remove the issues/4 part and it should work.

Oh now I got it, the extension tries to match that string. I initially thought that the `$$` could be enabled by taking any link `http://my.cool.link.com` and transforming it to `http://my.cool.link.com?activate&inlineMath=$`. Using either the badge or a link as in https://github.com/nschloe/green-pi/issues/4#issuecomment-624146020 is fine... _on github_.

We use zenhub for project management (that is somehow a superset of github). I tried to open in zenhub an existing issue with working math on the `github.com` domain, but in the zenhub domain math is not rendered. Is there any limitation / workaround?

**Comment by nschloe** [comment]
> Is there any limitation

Not by Green Pi. Link?

**Comment by nschloe** [comment]
> and transforming it to http://my.cool.link.com?activate&inlineMath=

Perhaps it would make sense to add that, too.

**Comment by diegoferigo** [comment]
> Not by Green Pi. Link?

Mmh difficult question. It requires an account. I think that the limitation here is that the github issue is opened in something like an hovering element in the same webpage:

![Screenshot_20200505_190702](https://user-images.githubusercontent.com/469199/81094436-ca4ded80-8f03-11ea-9001-612ed0199edb.png)

**Comment by nschloe** [comment]
Can't tell.

**Comment by diegoferigo** [comment]
Ok, thanks anyway @nschloe, if I find a way to reproduce the problem I let you know. Thank so much for your support!

**Comment by nschloe** [comment]
Just guessing: If the issue is loaded after page load has completed, then the extension doesn't see the badge. It only checks once right after page load.

**Comment by diegoferigo** [comment]
Yes that's what I suspect. Btw also other extension I tried in the past didn't work.
