### ISSUE TITLE
Deleted from Chrome Web Store?

### ISSUE THREAD

**Issue by eggplants** [nschloe/purple-pi#87]
Currently this package's page on Chrome Web Store is 404.
https://chrome.google.com/webstore/detail/purple-pi/ingbbliecffofmmokknelnijicfcgolb?authuser=0&hl=sk
Intentionally?

**Comment by nschloe** [comment]
Purple Pi is deprecated. Please read the first word of the main readme.

**Comment by eggplants** [comment]
Sorry for my overlook. Thanks!
